version: '3.0'

networks:
  monitor-net:
    external:
      name: monitor

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

services:

  prometheus:
    image: prom/prometheus:v2.12.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: always
    expose:
      - 9090
    labels:
     - "traefik.backend=prometheus"
     - "traefik.docker.network=monitor-net"
     - "traefik.frontend.rule=Host:prom.ddns.me"
     - "traefik.enable=true"
     - "traefik.port=9090"
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager:v0.19.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: always
    expose:
      - 9093
    labels:
      - "traefik.backend=alertmanager"
      - "traefik.docker.network=monitor-net"
      - "traefik.frontend.rule=Host:alert.ddns.me"
      - "traefik.enable=true"
      - "traefik.port=9093"
    networks:
      - monitor-net
  
  nodeexporter:
    image: prom/node-exporter:v0.18.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always
    expose:
      - 9100
    labels:
      - "traefik.backend=nodeexporter"
      - "traefik.docker.network=monitor-net"
      - "traefik.frontend.rule=Host:node.ddns.me"
      - "traefik.enable=true"
      - "traefik.port=9100"
    networks:
      - monitor-net

  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: always
    expose:
      - 8080
    labels:
      - "traefik.backend=cadvisor"
      - "traefik.docker.network=monitor-net"
      - "traefik.frontend.rule=Host:cadvisor.ddns.me"
      - "traefik.enable=true"
      - "traefik.port=8080"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:6.3.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin+123}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    expose:
      - 3000
    labels:
      - "traefik.backend=grafana"
      - "traefik.docker.network=monitor-net"
      - "traefik.frontend.rule=Host:dashboard.ddns.me"
      - "traefik.enable=true"
      - "traefik.port=3000"
    networks:
      - monitor-net

  pushgateway:
    image: prom/pushgateway:v0.9.1
    container_name: pushgateway
    restart: always
    expose:
      - 9091
    labels:
      - "traefik.backend=pushgateway"
      - "traefik.docker.network=monitor-net"
      - "traefik.frontend.rule=Host:push.ddns.me"
      - "traefik.enable=true"
      - "traefik.port=9091"
    networks:
      - monitor-net
